[katago]
engine = "c:/katago/katago.exe"
model = "C:/katago/model.bin.gz"
config = "C:/katago/analysis.cfg"

[save]
ai_branches = true
ai_winrate = true
ai_visits = true
human_winrate = false
as_new_file = true

[analysis]
max_visits = 1000
rules = "chinese"
komi = 7.5

[batch]
cooldown = 60